/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://mxxvko6sznfm7ejc23utsm6yeu.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-cc2mw7n3vfdmzcglpof24ohnty",
    "aws_cognito_identity_pool_id": "us-east-2:aa5f4b37-4ec8-41cd-8163-b7ca4d073489",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_FN2u1Dhr4",
    "aws_user_pools_web_client_id": "5u4m399s1r9q5ok1dr02tptnrn",
    "oauth": {}
};


export default awsmobile;
